version: "3.9"
services:
  postgres-db:
    image: postgres:16
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: campusorbit
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - campusorbit-test-network

networks:
  campusorbit-test-network:
    driver: bridge

volumes:
  postgres-data:
  # redis-data:
