version: "3.9"
services:
  postgres-db:
    image: postgres:16
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: campusorbit
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - campusorbit-test-network

  redis-cache:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - campusorbit-test-network

networks:
  campusorbit-test-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
