version: "3.8"

services:
  app:
    build: .
    command: npm run dev
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/your_database_name
    volumes:
      - ./:/app
      - prisma:/app/prisma
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: your_database_name
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: {}
  prisma: {}
