export const benefits = [
  {
    id: "0",
    title: "Ask anything",
    text: "Lets users quickly find answers to their questions without having to search through multiple sources.",
    backgroundUrl: "./bg/card-1.svg",
    iconUrl: "/icons/icon-1.svg",
    imageUrl: "/icons/image-2.png",
  },
  {
    id: "1",
    title: "Improve everyday",
    text: "The app uses natural language processing to understand user queries and provide accurate and relevant responses.",
    backgroundUrl: "card-2.svg",
    iconUrl: "/icons/icon-2.svg",
    imageUrl: "/icons/image-2.png",
    light: true,
  },
  {
    id: "2",
    title: "Connect everywhere",
    text: "Connect with the AI chatbot from anywhere, on any device, making it more accessible and convenient.",
    backgroundUrl: "card-3.svg",
    iconUrl: "/icons/icon-3.svg",
    imageUrl: "/icons/image-2.png",
  },
  {
    id: "3",
    title: "Fast responding",
    text: "Lets users quickly find answers to their questions without having to search through multiple sources.",
    backgroundUrl: "card-4.svg",
    iconUrl: "/icons/icon-4.svg",
    imageUrl: "/icons/image-2.png",
    light: true,
  },
  {
    id: "4",
    title: "Ask anything",
    text: "Lets users quickly find answers to their questions without having to search through multiple sources.",
    backgroundUrl: "card-5.svg",
    iconUrl: "/icons/icon-2.svg",
    imageUrl: "/icons/image-2.png",
  },
  {
    id: "5",
    title: "Improve everyday",
    text: "The app uses natural language processing to understand user queries and provide accurate and relevant responses.",
    backgroundUrl: "card-6.svg",
    iconUrl: "/icons/icon-1.svg",
    imageUrl: "/icons/image-2.png",
  },
]
